# Generated by Django 4.1.5 on 2023-01-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbieName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('emailAddress', models.EmailField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='status', max_length=100)),
                ('status', models.CharField(choices=[('Student', 'Student'), ('Work', 'Work')], default='status', max_length=50)),
                ('longitude', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(choices=[('Marrakech', 'Marrakech'), ('Fès', 'Fès'), ('Chefchaouen', 'Chefchaouen'), ('Essaouira', 'Essaouira'), ('Tanger', 'Tanger'), ('Casablanca', 'Casablanca'), ('Rabat', 'Rabat'), ('Meknès', 'Meknès'), ('Agadir', 'Agadir'), ('Ouarzazate', 'Ouarzazate'), ('Asilah', 'Asilah'), ('Tétouan', 'Tétouan'), ('Merzouga', 'Merzouga'), ('El Jadida', 'El Jadida'), ('Tinghir', 'Tinghir'), ('Ifrane', 'Ifrane'), ('Taroudant ', 'Taroudant'), ('Larache', 'Larache'), ('Aït Ben Haddou', 'Aït Ben Haddou'), ('Al Hoceïma', 'Al Hoceïma'), ('Oujda', 'Oujda'), ('Sidi Ifni', 'Sidi Ifni'), ('Azrou', 'Azrou'), ('Béni Mellal', 'Béni Mellal'), ('Midelt', 'Midelt'), ('Safi', 'Safi'), ('Taza', 'Taza'), ('Martil', 'Martil'), ('Oued Zem', 'Oued Zem'), ('Sefrou', 'Sefrou'), ('Taourirt', 'Taourirt'), ('Guercif', 'Guercif'), ('Tiflet', 'Tiflet'), ('Ouazzane', 'Ouazzane'), ('Youssoufia', 'Youssoufia'), ('Ksar El-Kébir', 'Ksar El-Kébir'), ('Fnideq', 'Fnideq'), ('Sidi Kacem', 'Sidi Kacem'), ('Saïdia', 'Saïdia'), ("M'diq", "M'diq"), ('Tiznit', 'Tiznit'), ('Moulay Idriss', 'Moulay Idriss'), ('Zerhoun', 'Zerhoun'), ('Guelmim', 'Guelmim'), ('Mohammédia', 'Mohammédia'), ('Imlil', 'Imlil'), ('Nador', 'Nador'), ('Berrchid', 'Berrchid'), ('Settat', 'Settat'), ('Berkane', 'Berkane')], default='Casablanca', max_length=50)),
                ('bio', models.TextField(blank=True, default='No Bio', max_length=600, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateField(auto_now=True, null=True)),
                ('last_login', models.DateField(auto_now=True, null=True)),
                ('hoobie', models.ManyToManyField(to='authenticationApp.hobbies')),
            ],
        ),
    ]
