# Generated by Django 4.1.5 on 2023-01-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0003_remove_userprofile_lastname_userprofile_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstname',
            new_name='user',
        ),
    ]
